name: Commit

on:
  push:
    paths:
      - 'stage*/**'
      - 'build*.sh'
      - 'config'
      - 'export*/**'
      - '.github/**'

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends quilt qemu-user-static debootstrap libarchive-tools qemu-utils
      - name: Build
        run: sudo ./build.sh -c config
      - name: Create tar
        run: tar -czf biondemos-os-full.tar.gz deploy/biondemos-os-full.img
      - name: Create zip
        run: zip biondemos-os-full.zip deploy/biondemos-os-full.img
      - name: Upload tar
        uses: actions/upload-artifact@v3
        with:
          name: custom-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
          path: ${{ runner.temp }}/biondemos-os-full.tar.gz
          retention-days: 7
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: custom-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
          path: ${{ runner.temp }}/biondemos-os-full.zip
          retention-days: 7