name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends quilt qemu-user-static debootstrap libarchive-tools qemu-utils
      - name: Build
        run: sudo ./build.sh -c config
      - name: Create tar
        run: tar -czf biondemos-os-full.tar.gz deploy/biondemos-os-full.img
      - name: Create zip
        run: zip biondemos-os-full.zip deploy/biondemos-os-full.img
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - name: Upload tar Release Asset
        uses: sekwah41/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: biondemos-os-full.tar.gz
          asset_name: biondemos-os-full.tar.gz
          asset_content_type: application/gzip
      - name: Upload zip Release Asset
        uses: sekwah41/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: biondemos-os-full.zip
          asset_name: biondemos-os-full.zip
          asset_content_type: application/zip